version: '3.9'
services:
  web:
    image: eclipse-mosquitto:latest
    container_name: mqtt
    restart: always
    ports:
      - ${MQTT_PORT}:1883
      - ${MQTTS_PORT}:9001
    networks:
      - default
    volumes:
      - ./config/:/mosquitto/config/:ro
      - ./log/:/mosquitto/log/
      - data:/mosquitto/data/

networks:
  default:
    name: docker_mosquitto_network
    driver: bridge

volumes:
  data:
    name: docker_mosquitto_data
    driver: local